=== MuAshrafAlii/ITI-Labs/XML/Lab 2/employee.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT employees (employee+)>
<!ELEMENT employee (name, phones, addresses, email)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT phones (phone+)>
<!ELEMENT phone (#PCDATA)>
<!ATTLIST phone
          type (home | work | mobile) #REQUIRED>
<!ELEMENT addresses (address+)>
<!ELEMENT address (street, buildingNumber, Region, city, country)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT buildingNumber (#PCDATA)>
<!ELEMENT Region (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT email (#PCDATA)>

=== MuAshrafAlii/ITI-Labs/XML/Lab 2/employees.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE employees SYSTEM "employee.dtd">
<employees>
	<employee>
		<name>Muhammad</name>
		<phones>
			<phone type="home">035778832 -</phone>
			<phone type="work">035881123 -</phone>
			<phone type="mobile">01176192728</phone>
		</phones>
		<addresses>
			<address>
				<street>Abo keer</street>
				<buildingNumber>15</buildingNumber>
				<Region>Sidi Gaber</Region>
				<city>Alexandria</city>
				<country>Egypt / </country>
			</address>
			<address>
				<street>Portsaied</street>
				<buildingNumber>4</buildingNumber>
				<Region>Kamp Chezar</Region>
				<city>Alex</city>
				<country>Egypt</country>
			</address>
		</addresses>
		<email>Muhammad@gmail.com</email>
	</employee>
	<employee>
		<name>Ashraf</name>
		<phones>
			<phone type="home">025117734 -</phone>
			<phone type="work">026229942 -</phone>
			<phone type="mobile">01173645382</phone>
		</phones>
		<addresses>
			<address>
				<street>7dayek el m3ady</street>
				<buildingNumber>10</buildingNumber>
				<Region>Elm3ady</Region>
				<city>Cairo</city>
				<country>Egypt / </country>
			</address>
			<address>
				<street>shobra street</street>
				<buildingNumber>14</buildingNumber>
				<Region>shobra</Region>
				<city>Cairo</city>
				<country>Egypt</country>
			</address>
		</addresses>
		<email>Ashraf@gmail.com</email>
	</employee>
</employees>
